"""Quet project va goi y file nao nen import vao bang TiDB nao.

Muc luc:
1. Tim CSV/JSON/model artifact trong data, outputs, src va models.
2. Doc header/hash/sample cua tung file du lieu.
3. Sinh report mapping de xem file nao vao typed table hay raw staging.
"""

from __future__ import annotations

import argparse
import csv
import sys
from collections import Counter, defaultdict
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[2]
SRC_DIR = ROOT_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from database.tidb_import_utils import (  # noqa: E402
    DEFAULT_SCAN_ROOTS,
    iter_source_files,
    read_csv_header_sample,
    recommend_data_file,
    relative_path,
    source_group,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Inspect project data files and recommend TiDB import targets"
    )
    parser.add_argument(
        "--inventory-csv",
        type=Path,
        default=ROOT_DIR / "data" / "tidb_import" / "source_inventory.csv",
    )
    parser.add_argument(
        "--report-md",
        type=Path,
        default=ROOT_DIR / "data" / "tidb_import" / "import_plan.md",
    )
    return parser.parse_args()


def build_inventory() -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for path in iter_source_files(DEFAULT_SCAN_ROOTS):
        recommendation = recommend_data_file(path)
        header: list[str] = []
        sample: list[str] = []
        if path.suffix.lower() == ".csv":
            header, sample = read_csv_header_sample(path)
        rows.append(
            {
                "source_path": relative_path(path),
                "source_group": source_group(path),
                "file_type": path.suffix.lower().lstrip("."),
                "size_bytes": path.stat().st_size,
                "recommended_target_table": recommendation.target_table,
                "transform_action": recommendation.transform,
                "reason": recommendation.reason,
                "column_count": len(header),
                "columns": ", ".join(header),
                "sample_first_values": " | ".join(sample[:8]),
            }
        )
    return rows


def write_inventory(rows: list[dict[str, object]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "source_path",
        "source_group",
        "file_type",
        "size_bytes",
        "recommended_target_table",
        "transform_action",
        "reason",
        "column_count",
        "columns",
        "sample_first_values",
    ]
    with path.open("w", encoding="utf-8-sig", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_report(rows: list[dict[str, object]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    by_target: dict[str, list[dict[str, object]]] = defaultdict(list)
    for row in rows:
        by_target[str(row["recommended_target_table"])].append(row)

    lines = [
        "# TiDB import plan",
        "",
        "Generated by `src/database/inspect_tidb_import_sources.py`.",
        "",
        "## Summary",
        "",
        "| Target table | Files |",
        "|---|---:|",
    ]
    for target, count in sorted(Counter(row["recommended_target_table"] for row in rows).items()):
        lines.append(f"| `{target}` | {count} |")

    lines.extend(
        [
            "",
            "## Mapping",
            "",
            "| Target table | Transform | Examples |",
            "|---|---|---|",
        ]
    )
    for target, target_rows in sorted(by_target.items()):
        transforms = sorted({str(row["transform_action"]) for row in target_rows})
        examples = "<br>".join(f"`{row['source_path']}`" for row in target_rows[:8])
        if len(target_rows) > 8:
            examples += f"<br>... and {len(target_rows) - 8} more"
        lines.append(f"| `{target}` | {', '.join(transforms)} | {examples} |")

    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- `live_hourly_observations` and `live_hourly_predictions` are typed production tables.",
            "- Legacy raw/model/evaluation CSV files go to `raw_csv_import_rows` so no columns are lost.",
            "- Model metadata JSON files can populate `model_registry`; model binaries are referenced by path only.",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    rows = build_inventory()
    write_inventory(rows, args.inventory_csv.resolve())
    write_report(rows, args.report_md.resolve())
    print(f"Inspected {len(rows)} data files")
    print(f"Wrote inventory: {args.inventory_csv.resolve()}")
    print(f"Wrote report: {args.report_md.resolve()}")


if __name__ == "__main__":
    main()
